name: Build Electron App for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Rebuild Electron Modules
        run: npx electron-rebuild

      - name: Run Build
        run: npm run build

      - name: Package Electron App
        run: npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ElectronAppDist
          path: dist/**

    env:
      ELECTRON_CACHE: "C:\electron_cache"
      ELECTRON_BUILDER_CACHE: "C:\electron_builder_cache"
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
